openapi: 3.0.0
info:
  title: 实验室管理信息系统
  description: 实验室管理信息系统
  contact:
    email: fzxseraching@163.com
  version: 1.0.0
paths:
  /CheckCloth/inf_list:
    get:
      tags:
        - CheckCloth
      summary: 列出数据
      description: '待验布列表接口,默认显示所有的数据，根据条件的不同进行搜索'
      operationId: inf_list
      parameters:
        -
          name: roid
          in: query
          description: 收料单号
          schema:
            type: string
        -
          name: page_num
          in: query
          description: 页码
          schema:
            type: integer
        -
          name: page_count
          in: query
          description: 当前页面显示的数据量
          schema:
            type: integer
        -
          name: mmfname
          in: query
          description: 物料名字
          schema:
            type: string
        -
          name: mmfcode
          in: query
          description: 物料编号
          schema:
            type: string
        -
          name: providername
          in: query
          description: 供应商名字
          schema:
            type: string
        -
          name: mpsid
          in: query
          description: 制单号
          schema:
            type: string
        -
          name: state
          in: query
          description: 状态：1：待验布；2：已验布；默认所有
          schema:
            type: string
      responses:
        '200':
          description: '返回结果的data是一个Json数组，如：[{...},{...}]'
          content:
            application/json:
              schema:
                type: object
              example:
                code: 返回码：200成功、400失败
                msg: 返回消息
                info:
                  all: 所有数量
                  alreadycheck: 已验布的数量
                  uncheck: 未验布的数量
                  '0': { MPSName: 款名, MPSCode: 款号, Name: 物料名字, PicturePath: 图片路径, Color: 颜色, ColorID: 颜色ID, MPSID: 制单号, ROID: 收料单号, Model: 合同门幅, POID: 采购单号, FGWeight: 克重, MultQty: 数量, MultUnit: 单位, Code: 款号, BatchNO: 缸号, FillDate: 收料时间, UsedDate: 消耗时间, ShortName: 供应商名字, MatBarCodeNum: 匹/卷数, QCID: 检验单号, CheckState: 检验状态，已审核，未审核, SamplState: 及格状态，及格/不及格 }
        '400':
          description: 查找失败
tags:
  -
    name: Admin
    description: 后台管理
